spring:
  application:
    name: Mugen
#    mailersend:
#      api-key: ${MAILERSEND_API_KEY}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/mugen?createDatabaseIfNotExist=true
    username: root
    password: Toni2020@
  jpa:
    show-sql: true
  jwt:
    secret-key: ${JWT_SECRET}
    access-token-expiration-time: 604800 #  7 days in seconds TODO: change to 900 `15 mins in seconds` for production
    refresh-token-expiration-time: 604800 # 604800 is 7 days in seconds
    reset-password-token-expiration-time: 900 # 15 mins in seconds